Tested current methods
brianwchou/Soldity-Stack-Example pull request #1
Opened 2019-08-08 17:39 UTC by brianwchou

##Description

test each of the following:
- [ x ] peek()
- [ x ] push()
- [ x ] pop()

2019-08-09 01:14 UTC, ejwessel commented
@brianwchou lets also add
https://www.npmjs.com/package/ganache-time-traveler

You can do this in another PR

2019-08-09 01:15 UTC, ejwessel requested changes
Waiting on https://github.com/brianwchou/Soldity-Stack-Example/pull/2

2019-08-09 01:15 UTC, ejwessel commented on test/Stack.test.js
> -    beforeEach(async () => {
add https://www.npmjs.com/package/ganache-time-traveler

2019-08-09 01:34 UTC, ejwessel requested changes

2019-08-09 01:34 UTC, ejwessel commented on test/Stack.test.js
> +        truffleAssert.fails(stack.push(5))
use `reverts()`

You also need an await at the beginning of this line

2019-08-09 01:34 UTC, ejwessel commented on test/Stack.test.js
> +        truffleAssert.reverts(stack.peek(), 'stack needs to have a value')
you are missing an await at the beginning of this line.

2019-08-09 22:26 UTC, brianwchou commented on test/Stack.test.js
> -    beforeEach(async () => {
Not sure how much this matters but tests run slightly faster without time traveler.

2019-08-10 03:43 UTC, ejwessel commented
waiting for https://github.com/brianwchou/Soldity-Stack-Example/pull/8

2019-08-10 03:44 UTC, ejwessel commented on test/Stack.test.js
> -    beforeEach(async () => {
Good eye. At this point I'm ok with it.

2019-08-10 04:14 UTC, ejwessel requested changes
requesting.

2019-08-10 04:14 UTC, ejwessel commented on test/Stack.test.js
> +    it('push() increments size of stack', async() => {
Can we have two describe blocks?
- the first one will test initial state
- the second one will test setting state

2019-08-12 02:34 UTC, ejwessel commented on test/Stack.test.js
> +    it('push() increments size of stack', async() => {
ignore this. let's do this in another pr

2019-08-12 02:34 UTC, ejwessel approved these changes
LGTM

2019-08-12 02:39 UTC, merged